// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.SqliteDbMigrations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201207013556_SeedActivities")]
    partial class SeedActivities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 12, 6, 20, 35, 55, 671, DateTimeKind.Local).AddTicks(7578),
                            Summary = "Freezing",
                            TemperatureC = -15
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 12, 7, 20, 35, 55, 677, DateTimeKind.Local).AddTicks(4269),
                            Summary = "Chilly",
                            TemperatureC = 16
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 12, 8, 20, 35, 55, 677, DateTimeKind.Local).AddTicks(4444),
                            Summary = "Cool",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 12, 9, 20, 35, 55, 677, DateTimeKind.Local).AddTicks(4461),
                            Summary = "Mild",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 12, 10, 20, 35, 55, 677, DateTimeKind.Local).AddTicks(4470),
                            Summary = "Warm",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 12, 11, 20, 35, 55, 677, DateTimeKind.Local).AddTicks(4477),
                            Summary = "Hot",
                            TemperatureC = 40
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 12, 12, 20, 35, 55, 677, DateTimeKind.Local).AddTicks(4484),
                            Summary = "Scorching",
                            TemperatureC = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
