// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201205203120_SeedWeatherForcasts")]
    partial class SeedWeatherForcasts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 12, 5, 15, 31, 19, 334, DateTimeKind.Local).AddTicks(9275),
                            Summary = "Freezing",
                            TemperatureC = -15
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 12, 6, 15, 31, 19, 338, DateTimeKind.Local).AddTicks(2934),
                            Summary = "Chilly",
                            TemperatureC = 16
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 12, 7, 15, 31, 19, 338, DateTimeKind.Local).AddTicks(3024),
                            Summary = "Cool",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 12, 8, 15, 31, 19, 338, DateTimeKind.Local).AddTicks(3032),
                            Summary = "Mild",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 12, 9, 15, 31, 19, 338, DateTimeKind.Local).AddTicks(3036),
                            Summary = "Warm",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2020, 12, 10, 15, 31, 19, 338, DateTimeKind.Local).AddTicks(3040),
                            Summary = "Hot",
                            TemperatureC = 40
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2020, 12, 11, 15, 31, 19, 338, DateTimeKind.Local).AddTicks(3044),
                            Summary = "Scorching",
                            TemperatureC = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
